create table cidade (estado_id bigint, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nom_cozinha varchar(30), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissaoes (grupo_id bigint not null, permissaoes_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (aberto bit, ativo bit, taxa_frete decimal(38,2), cozinha_id bigint, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table `restaurante_forma_pagamento,` (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6), id bigint not null auto_increment, nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
create table usuario_grupos (grupos_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table restaurante_produtos add constraint UK_oflwn902s6jtogedwka7vx954 unique (produtos_id);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissaoes add constraint FKkxoyu5c56yekdgb1yg2it0h5v foreign key (permissaoes_id) references permissao (id);
alter table grupo_permissaoes add constraint FK22h74nnf6h1paol3s3f997x0x foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table `restaurante_forma_pagamento,` add constraint FKsxn1ov72hr9655ll0r0kbn91r foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table `restaurante_forma_pagamento,` add constraint FKe1j9g5iu6x78sfwyha2crmmv6 foreign key (restaurante_id) references restaurante (id);
alter table restaurante_produtos add constraint FKg4ysuq1sw783poblhs9uuueep foreign key (produtos_id) references produto (id);
alter table restaurante_produtos add constraint FKti5of5m60kqvc6dt63ynj30u7 foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupos add constraint FK92ff1v8fkwig9tqv9bk4nvi0t foreign key (grupos_id) references grupo (id);
alter table usuario_grupos add constraint FK158r9y55ufwykh675ddt8kb43 foreign key (usuario_id) references usuario (id);
INSERT into cozinha (id,nom_cozinha) VALUES (1,'tailandesa');
INSERT into cozinha (id,nom_cozinha) VALUES (2,'Indiana');
INSERT into cozinha (id,nom_cozinha) VALUES (3,'mexicana');
INSERT into cozinha (id,nom_cozinha) VALUES (4,'arabe');
INSERT into forma_pagamento (id,descricao) VALUES (1,'cartao debito');
INSERT into forma_pagamento (id,descricao) VALUES (2,'pix');
INSERT into forma_pagamento (id,descricao) VALUES (3,'cartao credito');
INSERT into estado (id,nome)  VALUES (1,'RS');
INSERT into estado (id,nome)  VALUES (2,'SC');
INSERT into estado (id,nome)  VALUES (3,'PR');
INSERT into estado (id,nome)  VALUES (4,'SP');
INSERT INTO cidade (id,nome,estado_id) VALUES (1,'porto alegre',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (2,'viamao',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (3,'canoas',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (4,'gravatai',1);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai gourmet',10,1,utc_timestamp,utc_timestamp);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai delivery',9.50,1,utc_timestamp,utc_timestamp);
INSERT into trestaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('tuk tuk comida',15,2,utc_timestamp,utc_timestamp);
INSERT INTO `restaurante_forma_pagamento,` (`forma_pagamento_id`, `restaurante_id`) VALUES ('1', '1'), ('1', '2'),('1','3'),('3','1'),('2','1');
create table cidade (estado_id bigint, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nom_cozinha varchar(30), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissaoes (grupo_id bigint not null, permissaoes_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (aberto bit, ativo bit, taxa_frete decimal(38,2), cozinha_id bigint, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table `restaurante_forma_pagamento,` (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6), id bigint not null auto_increment, nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
create table usuario_grupos (grupos_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table restaurante_produtos add constraint UK_oflwn902s6jtogedwka7vx954 unique (produtos_id);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissaoes add constraint FKkxoyu5c56yekdgb1yg2it0h5v foreign key (permissaoes_id) references permissao (id);
alter table grupo_permissaoes add constraint FK22h74nnf6h1paol3s3f997x0x foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table `restaurante_forma_pagamento,` add constraint FKsxn1ov72hr9655ll0r0kbn91r foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table `restaurante_forma_pagamento,` add constraint FKe1j9g5iu6x78sfwyha2crmmv6 foreign key (restaurante_id) references restaurante (id);
alter table restaurante_produtos add constraint FKg4ysuq1sw783poblhs9uuueep foreign key (produtos_id) references produto (id);
alter table restaurante_produtos add constraint FKti5of5m60kqvc6dt63ynj30u7 foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupos add constraint FK92ff1v8fkwig9tqv9bk4nvi0t foreign key (grupos_id) references grupo (id);
alter table usuario_grupos add constraint FK158r9y55ufwykh675ddt8kb43 foreign key (usuario_id) references usuario (id);
INSERT into cozinha (id,nom_cozinha) VALUES (1,'tailandesa');
INSERT into cozinha (id,nom_cozinha) VALUES (2,'Indiana');
INSERT into cozinha (id,nom_cozinha) VALUES (3,'mexicana');
INSERT into cozinha (id,nom_cozinha) VALUES (4,'arabe');
INSERT into forma_pagamento (id,descricao) VALUES (1,'cartao debito');
INSERT into forma_pagamento (id,descricao) VALUES (2,'pix');
INSERT into forma_pagamento (id,descricao) VALUES (3,'cartao credito');
INSERT into estado (id,nome)  VALUES (1,'RS');
INSERT into estado (id,nome)  VALUES (2,'SC');
INSERT into estado (id,nome)  VALUES (3,'PR');
INSERT into estado (id,nome)  VALUES (4,'SP');
INSERT INTO cidade (id,nome,estado_id) VALUES (1,'porto alegre',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (2,'viamao',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (3,'canoas',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (4,'gravatai',1);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai gourmet',10,1,utc_timestamp,utc_timestamp);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai delivery',9.50,1,utc_timestamp,utc_timestamp);
INSERT into trestaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('tuk tuk comida',15,2,utc_timestamp,utc_timestamp);
INSERT INTO `restaurante_forma_pagamento,` (`forma_pagamento_id`, `restaurante_id`) VALUES ('1', '1'), ('1', '2'),('1','3'),('3','1'),('2','1');
create table cidade (estado_id bigint, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nom_cozinha varchar(30), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissaoes (grupo_id bigint not null, permissaoes_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (aberto bit, ativo bit, taxa_frete decimal(38,2), cozinha_id bigint, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table `restaurante_forma_pagamento,` (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6), id bigint not null auto_increment, nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
create table usuario_grupos (grupos_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table restaurante_produtos add constraint UK_oflwn902s6jtogedwka7vx954 unique (produtos_id);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissaoes add constraint FKkxoyu5c56yekdgb1yg2it0h5v foreign key (permissaoes_id) references permissao (id);
alter table grupo_permissaoes add constraint FK22h74nnf6h1paol3s3f997x0x foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table `restaurante_forma_pagamento,` add constraint FKsxn1ov72hr9655ll0r0kbn91r foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table `restaurante_forma_pagamento,` add constraint FKe1j9g5iu6x78sfwyha2crmmv6 foreign key (restaurante_id) references restaurante (id);
alter table restaurante_produtos add constraint FKg4ysuq1sw783poblhs9uuueep foreign key (produtos_id) references produto (id);
alter table restaurante_produtos add constraint FKti5of5m60kqvc6dt63ynj30u7 foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupos add constraint FK92ff1v8fkwig9tqv9bk4nvi0t foreign key (grupos_id) references grupo (id);
alter table usuario_grupos add constraint FK158r9y55ufwykh675ddt8kb43 foreign key (usuario_id) references usuario (id);
INSERT into cozinha (id,nom_cozinha) VALUES (1,'tailandesa');
INSERT into cozinha (id,nom_cozinha) VALUES (2,'Indiana');
INSERT into cozinha (id,nom_cozinha) VALUES (3,'mexicana');
INSERT into cozinha (id,nom_cozinha) VALUES (4,'arabe');
INSERT into forma_pagamento (id,descricao) VALUES (1,'cartao debito');
INSERT into forma_pagamento (id,descricao) VALUES (2,'pix');
INSERT into forma_pagamento (id,descricao) VALUES (3,'cartao credito');
INSERT into estado (id,nome)  VALUES (1,'RS');
INSERT into estado (id,nome)  VALUES (2,'SC');
INSERT into estado (id,nome)  VALUES (3,'PR');
INSERT into estado (id,nome)  VALUES (4,'SP');
INSERT INTO cidade (id,nome,estado_id) VALUES (1,'porto alegre',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (2,'viamao',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (3,'canoas',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (4,'gravatai',1);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai gourmet',10,1,utc_timestamp,utc_timestamp);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai delivery',9.50,1,utc_timestamp,utc_timestamp);
INSERT into trestaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('tuk tuk comida',15,2,utc_timestamp,utc_timestamp);
INSERT INTO `restaurante_forma_pagamento,` (`forma_pagamento_id`, `restaurante_id`) VALUES ('1', '1'), ('1', '2'),('1','3'),('3','1'),('2','1');
create table cidade (estado_id bigint, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nom_cozinha varchar(30), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissaoes (grupo_id bigint not null, permissaoes_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (aberto bit, ativo bit, taxa_frete decimal(38,2), cozinha_id bigint, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6), id bigint not null auto_increment, nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
create table usuario_grupos (grupos_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table restaurante_produtos add constraint UK_oflwn902s6jtogedwka7vx954 unique (produtos_id);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissaoes add constraint FKkxoyu5c56yekdgb1yg2it0h5v foreign key (permissaoes_id) references permissao (id);
alter table grupo_permissaoes add constraint FK22h74nnf6h1paol3s3f997x0x foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table restaurante_produtos add constraint FKg4ysuq1sw783poblhs9uuueep foreign key (produtos_id) references produto (id);
alter table restaurante_produtos add constraint FKti5of5m60kqvc6dt63ynj30u7 foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupos add constraint FK92ff1v8fkwig9tqv9bk4nvi0t foreign key (grupos_id) references grupo (id);
alter table usuario_grupos add constraint FK158r9y55ufwykh675ddt8kb43 foreign key (usuario_id) references usuario (id);
INSERT into cozinha (id,nom_cozinha) VALUES (1,'tailandesa');
INSERT into cozinha (id,nom_cozinha) VALUES (2,'Indiana');
INSERT into cozinha (id,nom_cozinha) VALUES (3,'mexicana');
INSERT into cozinha (id,nom_cozinha) VALUES (4,'arabe');
INSERT into forma_pagamento (id,descricao) VALUES (1,'cartao debito');
INSERT into forma_pagamento (id,descricao) VALUES (2,'pix');
INSERT into forma_pagamento (id,descricao) VALUES (3,'cartao credito');
INSERT into estado (id,nome)  VALUES (1,'RS');
INSERT into estado (id,nome)  VALUES (2,'SC');
INSERT into estado (id,nome)  VALUES (3,'PR');
INSERT into estado (id,nome)  VALUES (4,'SP');
INSERT INTO cidade (id,nome,estado_id) VALUES (1,'porto alegre',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (2,'viamao',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (3,'canoas',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (4,'gravatai',1);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai gourmet',10,1,utc_timestamp,utc_timestamp);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai delivery',9.50,1,utc_timestamp,utc_timestamp);
INSERT into trestaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('tuk tuk comida',15,2,utc_timestamp,utc_timestamp);
INSERT INTO `restaurante_forma_pagamento,` (`forma_pagamento_id`, `restaurante_id`) VALUES ('1', '1'), ('1', '2'),('1','3'),('3','1'),('2','1');
create table cidade (estado_id bigint, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nom_cozinha varchar(30), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table grupo_permissaoes (grupo_id bigint not null, permissaoes_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (aberto bit, ativo bit, taxa_frete decimal(38,2), cozinha_id bigint, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_produtos (produtos_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6), id bigint not null auto_increment, nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
create table usuario_grupos (grupos_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table restaurante_produtos add constraint UK_oflwn902s6jtogedwka7vx954 unique (produtos_id);
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissaoes add constraint FKkxoyu5c56yekdgb1yg2it0h5v foreign key (permissaoes_id) references permissao (id);
alter table grupo_permissaoes add constraint FK22h74nnf6h1paol3s3f997x0x foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table restaurante_produtos add constraint FKg4ysuq1sw783poblhs9uuueep foreign key (produtos_id) references produto (id);
alter table restaurante_produtos add constraint FKti5of5m60kqvc6dt63ynj30u7 foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupos add constraint FK92ff1v8fkwig9tqv9bk4nvi0t foreign key (grupos_id) references grupo (id);
alter table usuario_grupos add constraint FK158r9y55ufwykh675ddt8kb43 foreign key (usuario_id) references usuario (id);
INSERT into cozinha (id,nom_cozinha) VALUES (1,'tailandesa');
INSERT into cozinha (id,nom_cozinha) VALUES (2,'Indiana');
INSERT into cozinha (id,nom_cozinha) VALUES (3,'mexicana');
INSERT into cozinha (id,nom_cozinha) VALUES (4,'arabe');
INSERT into forma_pagamento (id,descricao) VALUES (1,'cartao debito');
INSERT into forma_pagamento (id,descricao) VALUES (2,'pix');
INSERT into forma_pagamento (id,descricao) VALUES (3,'cartao credito');
INSERT into estado (id,nome)  VALUES (1,'RS');
INSERT into estado (id,nome)  VALUES (2,'SC');
INSERT into estado (id,nome)  VALUES (3,'PR');
INSERT into estado (id,nome)  VALUES (4,'SP');
INSERT INTO cidade (id,nome,estado_id) VALUES (1,'porto alegre',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (2,'viamao',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (3,'canoas',1);
INSERT INTO cidade (id,nome,estado_id) VALUES (4,'gravatai',1);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai gourmet',10,1,utc_timestamp,utc_timestamp);
INSERT into restaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('thai delivery',9.50,1,utc_timestamp,utc_timestamp);
INSERT into trestaurante (nome,taxa_frete,cozinha_id,data_cadastro,data_atualizacao) VALUES ('tuk tuk comida',15,2,utc_timestamp,utc_timestamp);
INSERT INTO `restaurante_forma_pagamento,` (`forma_pagamento_id`, `restaurante_id`) VALUES ('1', '1'), ('1', '2'),('1','3'),('3','1'),('2','1');
